### ISSUE TITLE
Reverse Proxy issue

### ISSUE THREAD

**Issue by That-Guy-Jack** [Caligatio/youtube-archiver#2]
Hi having issues with not being able to reverse proxy the WSS connection for the downloader, 

webpage works fine using local IP but unable to get the WSS connection to proxy properly 

tried a few things on google but nothing worked any ideas?

using apache2 on ubuntu 20

**Comment by Caligatio** [comment]
Just to make sure, you're not using the pre-built Docker image right?

I'm admittedly less familiar with using Apache to proxy websockets but have you seen https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel?

**Comment by That-Guy-Jack** [comment]
for the docker image ive downloaded the repo and made some small css changes and im running it with 
```
docker build . -t youtube-archiver

docker run -ti -d -p 8080:8080 youtube-archiver
```

currently running with these paramaters on the apache2 server but i still get a error about a WSS

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerAdmin Website@thatguyjack.co.uk
    RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
  	RewriteCond %{QUERY_STRING} transport=websocket    [NC]
  	RewriteRule /(.*)           ws://192.168.5.12:8080/$1 [P,L]
        ProxyPreserveHost On
        RewriteEngine on
		ProxyPass "/" "http://192.168.5.12:8080/"
    	ProxyPassReverse "/" "http://192.168.5.12:8080/"
        ServerName download.thatguyjack.co.uk
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
SSLCertificateFile *SSL*
SSLCertificateKeyFile *SSL*
Include *SSL*
</VirtualHost>
</IfModule>
```

with that config i still get this error,
![image](https://user-images.githubusercontent.com/56127525/127993360-f2019935-cbb2-47f9-b9db-5e9a07804b7e.png)

**Comment by Caligatio** [comment]
Maybe I have an idea!

Change the lines

    RewriteCond %{REQUEST_URI}  ^/socket.io
    RewriteRule /(.*)           ws://192.168.5.12:8080/$1

to 

    RewriteCond %{REQUEST_URI}  ^/api/status
    RewriteRule /(.*)           ws://192.168.5.12:8080/status

**Comment by That-Guy-Jack** [comment]
Changed the config still getting the same error which is anoying, 
![image](https://user-images.githubusercontent.com/56127525/127996537-933b5675-89eb-4312-9a09-6faf4df19a05.png)

**Comment by Caligatio** [comment]
I should have asked this earlier, are you putting Apache2 in front of the Docker container or are you installing Apache2 in the container in lieu of nginx?

My above advice was thinking you were using it in lieu of nginx (which was probably a bad assumption), if it's in front of nginx, change:

    RewriteCond %{REQUEST_URI}  ^/socket.io
    RewriteRule /(.*)           ws://192.168.5.12:8080/$1

to 

    RewriteCond %{REQUEST_URI}  ^/api/status
    RewriteRule /(.*)           ws://192.168.5.12:8080/$1

The above reverts my previous idea of changing the `RewriteRule` line while keeping my changes to the `RewriteCond` line.

**Comment by That-Guy-Jack** [comment]
Yeah the apache2 server is outside of the container (running on a seperate sevrer )

**Comment by That-Guy-Jack** [comment]
Got a  update, entering a URL and sending it to download works ( after a few mins it shows up in the downloads folder) But theres no feedback on the frontend page (assuming /api/status error is the issue)

**Comment by Caligatio** [comment]
Yea, the live update is through the web socket. Did my last set of changes make any difference? Do the apache error logs shed any light?

**Comment by That-Guy-Jack** [comment]
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        RemoteIPProxyProtocol On
	ServerAdmin Website@thatguyjack.co.uk
  	RewriteCond %{QUERY_STRING} transport=websocket    [NC]
	RewriteCond %{REQUEST_URI}  ^/api/status			[NC]
	RewriteRule /(.*)           ws://192.168.5.12:8080/$1
	ProxyPreserveHost On
	RewriteEngine on
	ProxyPass "/" "http://192.168.5.12:8080/"
    ProxyPassReverse "/" "http://192.168.5.12:8080/"
    ServerName download.thatguyjack.co.uk
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	SSLCertificateFile *SSL*
	SSLCertificateKeyFile *SSL*
	Include *SSL*
</VirtualHost>
</IfModule>
```
theres no errors in the error.log and access.log just has the get request with no other infomation 

it just seems to be a issue with the /api/status as /api/download seems to work fine for the post requests

**Comment by That-Guy-Jack** [comment]
going directly to https://download.thatguyjack.co.uk/api/status

brings up this error 
![image](https://user-images.githubusercontent.com/56127525/128001399-9187353b-a9f2-4dc3-9307-7ed2dd07855b.png)

vs /api/download

![image](https://user-images.githubusercontent.com/56127525/128001439-c531a465-76c5-4c52-ac02-b4791b23f290.png)

**Comment by Caligatio** [comment]
Grasping at straws here, does this work? https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Apache

**Comment by That-Guy-Jack** [comment]
Got some Good news its seems to work with that config 

![image](https://user-images.githubusercontent.com/56127525/128002398-62023f34-5e42-491e-a946-f5be6da672b4.png)


Config that works :
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	RemoteIPProxyProtocol On
	ServerAdmin Website@thatguyjack.co.uk
        <Location />
            ProxyPass http://192.168.5.12:8080/
            ProxyPassReverse http://192.168.5.12:8080/
            RewriteEngine on
            RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
            RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
            RewriteRule .* ws://192.168.5.12:8080%{REQUEST_URI} [P]
        </Location>
    ServerName download.thatguyjack.co.uk
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	SSLCertificateFile *SSL*
	SSLCertificateKeyFile *SSL*
	Include *SSL*
</VirtualHost>
</IfModule>
```

**Comment by Caligatio** [comment]
Huzzah! Tenth time is the charm :)
